### ISSUE TITLE
Can not load html page..

### ISSUE THREAD

**Issue by ghost** [amio/awesome-micro#20]
hello,
Thank you for your very helpful awesome-micro modules.
while developing micro services i need to load html page in response of service.
For example, In express nodejs framework We can give public folder route in response of api.
Is there any way to load public folder on particular route or in response of particular service ?

I hope you got my issue.
Thanks in advance.

```
const { send,buffer,text,json,createError } = require('micro')
const { router,get,post,options } = require('microrouter')
const cors = require('micro-cors')()

const docs = cors(async(req, res) => {
  sendFile('public/index.html');
})

const notfound = cors((req, res) => send(res, 200,"route not found"))

module.exports = router(
  get('/docs', docs),
  options('/*', notfound)
)
```

**Comment by amio** [comment]
You might need a router for it https://github.com/amio/awesome-micro#modules

**Comment by ghost** [comment]
i want to serve static html file in response .
For example we serve public folder in express nodejs framework.

**Comment by amio** [comment]
With express you use it's builtin router to serve static files and api, with micro you need a router too, but it's not builtin.

Besides, you can watch this issue too https://github.com/zeit/micro/issues/306

**Comment by ghost** [comment]
hello,
thanks for replying.

You mean there is no support of Router-level middleware or third party middleware in microservice.

**Comment by amio** [comment]
Yeap, no builtin support for middleware in `micro` so far.
