### ISSUE TITLE
Consider adding multipart/form-data parser

### ISSUE THREAD

**Issue by neist** [amio/awesome-micro#36]
Hi

I've created a `multipart/form-data` parser, that works well with Micro, because it's both streaming and asynchronous.

Link to module: [form-parser](https://github.com/neist/form-parser)

The API is very simple:
```js
// Dependencies
const parser = require('form-parser')
const { send } = require('micro')

// Create server
module.exports = async (req, res) => {
  // Parse request
  await parser(req, async field => {
    // Log info
    console.log(field) // { fieldType, fieldName, fieldContent }
  })

  // Reply with finished
  return send(res, 200, 'Parsing form succeded.')
}
```

It doesn't have "micro" in it's name, but perhabs it's suitable for this list? - just throwing it out there :-)

Feel free to close this issue if you think otherwise.

**Comment by amio** [comment]
Nice package!

It's a general purpose module that can be used with micro(not just micro-specific, which is great), while this list focus on the micro-specific parts of all these great packages, so if there was an wrapper for it to use only with micro, that would be more suitable in this list :D

**Comment by neist** [comment]
Fair enough. It follows the same asynchronous API, as other micro modules, so I thought I would suggest it. I'm closing this issue :-) Thank you for this great repository.
