### ISSUE TITLE
Consider add missing packages present on awesome-zeit

### ISSUE THREAD

**Issue by kandros** [amio/awesome-micro#8]
[awesome-zeit](https://github.com/zeit/awesome-zeit) used to list Micro related packages but now points to this repository instead.
Consider add packages that were previously present in awesome-zeit but not here.
the list is [here](https://github.com/zeit/awesome-zeit/commit/e0a9e7488d3cf7c9948df8ee096ad613fc596748)

**Comment by amio** [comment]
Sure, thanks for reminding 😃
